name: Package

on:
  push:

jobs:
  package:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/arm64/v8]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Prepare container
        run: docker buildx build -f ci/Dockerfile . -t libcreate --platform ${{ matrix.platform }} --load
      - name: Build
        run: docker run --platform ${{ matrix.platform }} -v ./output:/libcreate/_packages libcreate
